name: Executar script diariamente

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Executar script
        run: python scr/script.py  # Substitua pelo nome correto do arquivo
      
      - name: Verificar status do Git
        run: git status

      - name: Commit e push dos gráficos gerados
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add imagens/
          git commit -m "Atualização" || echo "Nenhuma alteração para commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
